imports: // This is the configuration for yiic console application.
// Any writable CConsoleApplication properties can be configured here.
return array(
        'basePath'=>dirname(__FILE__).DIRECTORY_SEPARATOR.'..',
        'name'=>'My Console Application',

        // preloading 'log' component
        'preload'=>array('log'),

        'import'=>array(
                'application.models.*',
                'application.components.*',
                'application.vendor.iachilles.eavactiverecord.*',
                'application.vendor.iachilles.eavactiverecord.datatypes.*',
                'application.vendor.iachilles.eavactiverecord.helpers.*',
        ),

        // application components
        'components'=>array(

                // database settings are configured in database.php
                'db'=>require(dirname(__FILE__).'/database.php'),

                'log'=>array(
                        'class'=>'CLogRouter',
                        'routes'=>array(
                                array(
                                        'class'=>'CFileLogRoute',
                                        'levels'=>'error, warning',
                                ),
                        ),
                ),

        ),
);      
    - { resource: // This is the database connection configuration.
return array(

        'connectionString' => 'mysql:host=localhost;dbname=classifieds',
        'emulatePrepare' => false,
        'username' => 'root',
        'password' => '',
        'charset' => 'utf8',
    'tablePrefix' => '',
    'schemaCachingDuration' => 3600,

); }
    - { resource: // uncomment the following to define a path alias
// Yii::setPathOfAlias('local','path/to/local-folder');

// This is the main Web application configuration. Any writable
// CWebApplication properties can be configured here.
return array(
    'basePath'=>dirname(dirname(__FILE__)),
        'name'=>'Доска объявлений',
        'language'=>'ru',

        // preloading 'log' component
        'preload'=>array('log'),

        // autoloading model and component classes
        'import'=>array(
                'application.models.*',
                'application.components.*',
                'application.vendor.iachilles.eavactiverecord.*',
                'application.vendor.iachilles.eavactiverecord.datatypes.*',
                'application.vendor.iachilles.eavactiverecord.helpers.*',
        ),

        'modules'=>array(
                // uncomment the following to enable the Gii tool
                /*
                'gii'=>array(
                        'class'=>'system.gii.GiiModule',
                        'password'=>'Enter Your Password Here',
                        // If removed, Gii defaults to localhost only. Edit carefully to taste.
                        'ipFilters'=>array('127.0.0.1','::1'),
                ),
                */
        ),

        // application components
        'components'=>array(

                'user'=>array(
                        // enable cookie-based authentication
                        'allowAutoLogin'=>true,
                ),

                'viewRenderer' => array(
                        'class' => 'application.vendor.yiiext.twig-renderer.ETwigViewRenderer',
                        'twigPathAlias' => 'application.vendor.twig.twig.lib.Twig',
                        'fileExtension' => '.twig',
                ),

                'eavCache' => array(
                        'class' => 'system.caching.CRedisCache'
                ),

                'cache' => array(
                        'class' => 'system.caching.CRedisCache',
                        'hostname' => '127.0.0.1',
                        'port' => 6379,
                        'database' => 0,
                ),

                // uncomment the following to enable URLs in path-format

                'urlManager'=>array(
                        'urlFormat'=>'path',
                        'showScriptName'=>false,
                        'rules'=>array(
                                '<controller:\w+>/<id:\d+>'=>'<controller>/view',
                                '<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
                                '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
                        ),
                ),


                // database settings are configured in database.php
                'db'=>require(dirname(__FILE__).'/database.php'),

                'authManager'=>array(
            'class'=>'CDbAuthManager',
            'connectionID'=>'db',
        ),

                'errorHandler'=>array(
                        // use 'site/error' action to display errors
                        'errorAction'=>YII_DEBUG ? null : 'site/error',
                ),

                'log'=>array(
                        'class'=>'CLogRouter',
                        'routes'=>array(
                                array(
                                        'class'=>'CFileLogRoute',
                                        'levels'=>'error, warning',
                                ),
                                // uncomment the following to show log messages on web pages

                                /*array(
                                        'class'=>'CWebLogRoute',
                                ),*/

                        ),
                ),

        ),

        // application-level parameters that can be accessed
        // using Yii::app()->params['paramName']
        'params'=>array(
                // this is used in contact page
                'adminEmail'=>'webmaster@example.com',
                // configure to match your sphinx configuration,
                // or comment to disable sphinxsearch
                'sphinx'=>array(
                        'dsn'=>'mysql:host=127.0.0.1;port=9306',
                        'user'=>'root',
                        'pass'=>'',
                        'indexes'=>array('rt'=>['rt_ad'], 'disc'=>['ix_ad']),
                ),
        ),
); }
    - { resource: return CMap::mergeArray(
        require(dirname(__FILE__).'/main.php'),
        array(
                'components'=>array(
                        'fixture'=>array(
                                'class'=>'system.test.CDbFixtureManager',
                        ),
                        /* uncomment the following to provide test database connection
                        'db'=>array(
                                'connectionString'=>'DSN for test database',
                        ),
                        */
                ),
        )
); }      
                                   
