# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Bandit is a security linter designed to find common security issues in Python code.
# This action will run Bandit on your codebase.
# The results of the scan will be found under the Security tab of your repository.

# https://github.com/marketplace/actions/bandit-scan is ISC licensed, by abirismyname
# https://pypi.org/project/bandit/ is Apache v2.0 licensed, by PyCQA

name: Bandit
on: /**
* CSS3 No-image Chupa-Chupsy candy 
* by @girlie_mac 
* http://girliemac.com/blog/2012/03/24/making-chupa-chups-using-css3-pseudo-elements/
*
* Please, do not compare this with the real one. 
* I feel pretty terrible making the awesome design by Salvador Dalí into some crap.
* But my point of this demo is that you can create the floral shape with CSS, using border-radius:50% and pseudo-element(s)
*/
html {
    background: #444;
    background: linear-gradient(135deg, #555, #222);
    min-height: 100%;
    margin: 0;
    padding: 2em;
}
p {
    margin: 0;    
    padding: 0;
}
body > div {
    margin: 30px
}
.chupa-chups {
    width: 300px;
    height: 300px;
    border-radius: 50%;
}
.chupa-chups.orange {
    background: orange;
    background: linear-gradient(325deg, gold 20%, orangered);
}
.chupa-chups.green {
    background: green;
    background: linear-gradient(325deg, YellowGreen 20%, darkgreen);
}
.chupa-chups.pink {
    background: HotPink;
    background: linear-gradient(325deg, HotPink 20%, FireBrick);
}
.chupa-chups.blue {
    background: MediumBlue;
    background: linear-gradient(325deg, RoyalBlue 20%, MediumBlue);
}
.chupa-chups p {
    z-index: 1;
    position: absolute;
    top: 26px; left: 10px;
    color: #ce1141;
    font-family: Pacifico, cursive;
    font-size: 68px;
    line-height: 70px;
    text-align: center;
    text-shadow: 1px 2px 0 #fff;
}
.floral-shape,  
.floral-shape::before, 
.floral-shape::after {
    width: 200px;       
    height: 200px;
    border-radius: 25%;
    border: 6px solid #ce1141;
    background: yellow;
    background: linear-gradient(325deg, yellow 30%, orange);
}
.floral-shape {
    position: relative;
    top: 42px;
    left: 42px;
}
.floral-shape::before {
    content: "";
    position: absolute;
    top: -3px; left: -3px; /* adjust for the border-width */
    background: linear-gradient(370deg, yellow 30%, orange);
    transform: rotate(45deg);
}
.floral-shape::after {
    content: "";
    position: absolute;
    border: 0 none;
    box-shadow: none;
}
  push: <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

<!-- Chupa-Chupsy Candy -->
<div>
<div class="chupa-chups orange">
    <div class="floral-shape">
        <p>Chupa<br/>Chups</p>
    </div>
</div>
</div>


<div>
<div class="chupa-chups green">
    <div class="floral-shape">
        <p>Chupa<br/>Chups</p>
    </div>
</div>
</div>


<div>
<div class="chupa-chups pink">
    <div class="floral-shape">
        <p>Chupa<br/>Chups</p>
    </div>
</div>
</div>


<div>
<div class="chupa-chups blue">
    <div class="floral-shape">
        <p>Chupa<br/>Chups</p>
    </div>
</div>
</div>
    branches: [ "main" ]
  pull_request: {"view":"split-vertical","seethrough":"","prefixfree":"1","page":"css"}
@nursultanramazanov
Comment

    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '45 7 * * 6'

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: # optional arguments
          # exit with 0, even with results found
          exit_zero: true # optional, default is DEFAULT
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
          # File or directory to run bandit on
          # path: # optional, default is .
          # Report only issues of a given severity level or higher. Can be LOW, MEDIUM or HIGH. Default is UNDEFINED (everything)
          # level: # optional, default is UNDEFINED
          # Report only issues of a given confidence level or higher. Can be LOW, MEDIUM or HIGH. Default is UNDEFINED (everything)
          # confidence: # optional, default is UNDEFINED
          # comma-separated list of paths (glob patterns supported) to exclude from scan (note that these are in addition to the excluded paths provided in the config file) (default: .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg)
          # excluded_paths: # optional, default is DEFAULT
          # comma-separated list of test IDs to skip
          # skips: # optional, default is DEFAULT
          # path to a .bandit file that supplies command line arguments
          # ini_path: # optional, default is DEFAULT

