# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable
# packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency review'
on: <keys>
    <key>
        <height>-220.000000000</height>
        <color-r>0</color-r>
        <color-g>0</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>-200.000000000</height>
        <color-r>0</color-r>
        <color-g>0</color-g>
        <color-b>80</color-b>
    </key>
    <key>
        <height>-170.000000000</height>
        <color-r>0</color-r>
        <color-g>30</color-g>
        <color-b>100</color-b>
    </key>
    <key>
        <height>-150.000000000</height>
        <color-r>0</color-r>
        <color-g>50</color-g>
        <color-b>102</color-b>
    </key>
    <key>
        <height>-125.000000000</height>
        <color-r>19</color-r>
        <color-g>108</color-g>
        <color-b>160</color-b>
    </key>
    <key>
        <height>-7.500000000</height>
        <color-r>24</color-r>
        <color-g>140</color-g>
        <color-b>205</color-b>
    </key>
    <key>
        <height>-2.500000000</height>
        <color-r>135</color-r>
        <color-g>206</color-g>
        <color-b>250</color-b>
    </key>
    <key>
        <height>-0.500000000</height>
        <color-r>176</color-r>
        <color-g>226</color-g>
        <color-b>255</color-b>
    </key>
    <key>
        <height>0.000000000</height>
        <color-r>0</color-r>
        <color-g>130</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>2.500000000</height>
        <color-r>0</color-r>
        <color-g>190</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>25.000000000</height>
        <color-r>0</color-r>
        <color-g>255</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>60.000000000</height>
        <color-r>55</color-r>
        <color-g>255</color-g>
        <color-b>55</color-b>
    </key>
    <key>
        <height>90.000000000</height>
        <color-r>102</color-r>
        <color-g>51</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>140.000000000</height>
        <color-r>128</color-r>
        <color-g>85</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>200.000000000</height>
        <color-r>172</color-r>
        <color-g>115</color-g>
        <color-b>57</color-b>
    </key>
    <key>
        <height>220.000000000</height>
        <color-r>255</color-r>
        <color-g>255</color-g>
        <color-b>255</color-b>
    </key>
</keys>
  pull_request: <keys>
    <key>
        <height>-220.000000000</height>
        <color-r>0</color-r>
        <color-g>0</color-g>
        <color-b>0</color-b>
    </key>
    <key>
        <height>-200.000000000</height>
        <color-r>0</color-r>
        <color-g>0</color-g>
        <color-b>80</color-b>
    </key>
    <key>
        <height>-170.000000000</height>
        <color-r>0</color-r>
        <color-g>30</color-g>
        <color-b>100</color-b>
    </key>
    <key>
        <height>-55.029998779</height>
        <color-r>0</color-r>
        <color-g>50</color-g>
        <color-b>102</color-b>
    </key>
    <key>
        <height>-31.409999847</height>
        <color-r>19</color-r>
        <color-g>108</color-g>
        <color-b>160</color-b>
    </key>
    <key>
        <height>-13.329999924</height>
        <color-r>24</color-r>
        <color-g>140</color-g>
        <color-b>205</color-b>
    </key>
    <key>
        <height>-2.000000000</height>
        <color-r>135</color-r>
        <color-g>206</color-g>
        <color-b>250</color-b>
    </key>
    <key>
        <height>0.000000000</height>
        <color-r>176</color-r>
        <color-g>226</color-g>
        <color-b>255</color-b>
    </key>
    <key>
        <height>0.779999971</height>
        <color-r>229</color-r>
        <color-g>218</color-g>
        <color-b>160</color-b>
    </key>
    <key>
        <height>5.929999828</height>
        <color-r>229</color-r>
        <color-g>218</color-g>
        <color-b>160</color-b>
    </key>
    <key>
        <height>7.820000172</height>
        <color-r>195</color-r>
        <color-g>168</color-g>
        <color-b>54</color-b>
    </key>
    <key>
        <height>10.210000038</height>
        <color-r>67</color-r>
        <color-g>177</color-g>
        <color-b>84</color-b>
    </key>
    <key>
        <height>44.229999542</height>
        <color-r>22</color-r>
        <color-g>119</color-g>
        <color-b>50</color-b>
    </key>
    <key>
        <height>60.540000916</height>
        <color-r>14</color-r>
        <color-g>106</color-g>
        <color-b>41</color-b>
    </key>
    <key>
        <height>76.239997864</height>
        <color-r>99</color-r>
        <color-g>180</color-g>
        <color-b>77</color-b>
    </key>
    <key>
        <height>85.739997864</height>
        <color-r>206</color-r>
        <color-g>206</color-g>
        <color-b>206</color-b>
    </key>
    <key>
        <height>220.000000000</height>
        <color-r>255</color-r>
        <color-g>255</color-g>
        <color-b>255</color-b>
    </key>
</keys>
    branches: [ "main" ]

# If using a dependency submission action in this workflow this permission will need to be set to:
#
# permissions:
#   contents: write
#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api
permissions:
  contents: read
  # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
        with:
          comment-summary-in-pr: always
        #   fail-on-severity: moderate
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
        #   retry-on-snapshot-warnings: true
