# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request: @font-face {
    branches: [ "main" ]

jobs: font-family: 'Windows 95';
  build: src: url('../fonts/w-95-sans-serif.woff2') format('woff2'),

    runs-on: ubuntu-latest

    steps: url('../fonts/w-95-sans-serif.woff') format('woff');
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: font-weight: normal;
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
