name: Greetings
on: [pull_request_target, issues]
jobs: #
  greeting: # "main" pseudo-component makefile.
    runs-on: ubuntu-latest
    permissions: #
      issues: write
      pull-requests: write
    steps: # (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)
    - uses: actions/first-interaction@v1
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
