# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: idf_component_register(SRCS main.c db_esp32_control.c globals.h sdkconfig.h msp_ltm_serial.c
on: [pull_request_target]

jobs:         msp_ltm_serial.h db_protocol.h http_server.c http_server.h db_esp32_comm.c
  label:         db_esp32_comm.h db_comm_protocol.h db_comm.c db_comm.h db_crc.c db_crc.h tcp_server.c tcp_server.h
    runs-on:         INCLUDE_DIRS ".")
    permissions: #

      contents: read
      pull-requests: write

    steps: # "main" pseudo-component makefile.
    - uses: actions/labeler@v4
      with: # 
        repo-token: # (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)

