# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: <input type="hidden" name="Ad[category_id]" value="{{model.category_id}}">
  release: <div class="row">
    {{ form.labelEx(model, 'category_id') }}
    {{ form.dropDownList(model, 'category_id', model.getCategoryList(App.request.getQuery('id')), {'empty':'выбрать'}) }}
    {{ form.error(model, 'category_id') }}
</div>
    types: [created]

jobs: {% extends 'views/layouts/main_old.twig' %}

{% block auxres %}
    {{ Yii.void(App.clientScript.registerCoreScript('jquery')) }}
    {{ Yii.void(App.clientScript.registerScriptFile(
        App.request.baseUrl~'/js/select2-3.5.4/select2.js')) }}
    {{ Yii.void(App.clientScript.registerCssFile(
        App.request.baseUrl~'/js/select2-3.5.4/select2.css')) }}
{% endblock auxres %}

{% block content %}

{{ Yii.void(App.clientScript.registerScriptFile(
    App.request.baseUrl~'/js/citiesDropDown.js', constant('CClientScript::POS_END'))) }}
<div class="form">
{% set form = this.beginWidget('CActiveForm', {
    'htmlOptions': {'enctype':'multipart/form-data'}
}) %}
{{ form.errorSummary(model) }}
{% if model.getCategoryList(App.request.getQuery('id')) %}
    {% include 'views/ad/_subcategory.twig' %}
{% else %}
    {% include 'views/ad/_inputhidden.twig' %}
{% endif %}
<div class="row">
    {{ form.labelEx(model, 'title') }}
    {{ form.textField(model, 'title') }}
    {{ form.error(model, 'title') }}
</div>
<div class="row">
    {{ form.labelEx(model, 'description') }}
    {{ form.textArea(model, 'description') }}
    {{ form.error(model, 'description') }}
</div>
{% for key in model.eavAttributes|keys %}
    {% if model.getEavVariants(key) %} 
        {% include 'views/eav/dropDown.twig' %}
    {% else %}
        {% include 'views/eav/textInput.twig' %}
    {% endif %}
{% endfor %}

<div class="row">
    {{ C.Html.label('Область', false) }}
    {{ C.Html.dropDownList(
        'region_id', 'empty', regions,
        {'empty':'---------- область ----------', 'id':'id_region'})
    }}
</div>
<div class="row">
    {{ C.Html.activeLabel(model, 'city_id') }}
    {{ C.Html.activeDropDownList(
        model, 'city_id', {},
        {'empty':'------------ город ------------', 'id':'id_city'})
    }}
</div>

{{ C.Html.activeLabel(photo, 'image') }}
{{ C.Html.activeFileField(photo, 'image', {'multiple':'multiple','name':'images[]'}) }}
{{ C.Html.error(photo, 'image') }}

<div class="row buttons">
    {{ C.Html.submitButton() }}
</div>
{{ Yii.void(this.endWidget()) }}
</div>

<script type="text/javascript">
  $('#id_region').select2();
  $('#id_city').select2();
</script>

{% endblock content %}
  build: {% extends 'views/layouts/main_old.twig' %}

{% block content %}
<h3>Выберите категорию</h3>
{{ Yii.void(App.clientScript.registerCoreScript('jquery')) }}
{{ Yii.void(App.clientScript.registerCssFile(App.request.baseUrl~'/css/create.css')) }}
{{ Yii.void(App.clientScript.registerScriptFile(App.request.baseUrl~'/js/new.js', constant('CClientScript::POS_END'))) }}
<table class="category-select">
    <tr>
        <td class="first-level">
        <ul>
        {% for model in models %}
        <li>
        <a class="category-link" href="{{ App.request.baseUrl~'/ad/create/'~model.id }}"
            data-id="{{model.id}}">{{model.title}}</a>
        </li>
        {% endfor %}
        </ul>
        </td>
        <td class="second-level">
            <ul></ul>
        </td>
        <td class="third-level">
            <ul></ul>
        </td>
    </tr>
</table>
{% endblock content %}

    runs-on: ubuntu-latest
    permissions: {% extends 'views/layouts/main_old.twig' %}

{% block content %}
    {{ Yii.void(App.clientScript.registerCssFile(App.request.baseUrl~'/css/adview.css')) }}
    <h3>{{ model.title }}</h3>
    <div class="ad-author-and-city">
        <div class="ad-author">Автор: {{ model.author.name }}</div>
        <div class="ad-city">Город: {{ model.city.name }}</div>
        <div class="clear"></div>
    </div>
    {% for attrName, attrValue in model.getEavAttributes() %}
        <div style="color:green">
            {{ attrName }} ({{ model.getAttributeLabel(attrName) }}):{{ attrValue }}
        </div>
    {% endfor %}
    <div class="ad-description">Содержимое: {{ model.description }}</div>
    <div>{{ model.getAttributeLabel('price') }}
      {% if (model.isEavAttributeEmpty('price')) %} 0
      {% else %} {{ model.price }}
      {% endif %}
    </div>
    <div class="ad-added">Добавлено: {{ model.added }}</div>
    <div class="ad-images">
        {% for photo in model.photos %}
        <div class="ad-image">
            <img src="/images/thumb/big_{{photo.id}}_{{photo.name}}">
        </div>
        {% endfor %}
        <div class="clear"></div>
    </div>
{% endblock content %}
      contents: read
      packages: write

    steps: <div class="col-sm-6 col-md-3 eav-attribute">
  {{ C.Html.label(
    form.model.getAttributeLabel(attribute)
    ~'('~form.model.getAttributeUnit(attribute)~'), от',
    attribute~'-min-id'
  ) }}
  {{ C.Html.textField(
    'search['~attribute~'][min]',
    value['min'],
    {
      'id': attribute~'-min-id',
      'class': 'form-control'
    }
  ) }}
</div>
<div class="col-sm-6 col-md-3 eav-attribute">
  {{ C.Html.label(
    form.model.getAttributeLabel(attribute)
    ~'('~form.model.getAttributeUnit(attribute)~'), до',
    attribute~'-max-id'
  ) }}
  {{ C.Html.textField(
    'search['~attribute~'][max]',
    value['max'],
    {
      'id': attribute~'-max-id',
      'class': 'form-control'
    }
  ) }}
</div>
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with: <div class="row">
    {{ C.Html.activeLabel(model, key) }}
    {{ C.Html.activeDropDownList(model, key, model.getEavVariants(key), {'empty':'выбрать'}) }}
    {{ C.Html.error(model, key) }}
</div>
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env: <div class="col-sm-6 col-md-3 eav-attribute">
  {{ C.Html.label(form.model.getAttributeLabel(attribute), attribute~'-id') }}
  {{ C.Html.dropDownList(
    'search['~attribute~']',
    value,
    form.model.getEavVariants(attribute),
    {
      'id': attribute~'-id',
      'empty':'выбрать',
      'class': 'form-control'
    }
  ) }}
</div>
        GITHUB_TOKEN: ${{ <div class="row">
{{ C.Html.activeLabel(model, key) }}
{{ C.Html.activeTextField(model, key) }}
{{ C.Html.error(model, key) }}
</div> }}
