name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:                   *busPacket = [some eligible packet]               
  build:              First the code looks if any refreshes need to go
    runs-on: ubuntu-latest

    strategy:                 Then it looks for data packets
      matrix:                  Otherwise, it starts looking for rows to close (in open page)
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js {{ matrix.node-version }}

      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
