name: PHP Composer

on: $ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    $ export PATH="$PATH:$PWD/depot_tools"
  push: $ mkdir $PWD/castanets && cd $PWD/castanets
        $ git clone https://github.com/Samsung/castanets src
        $ mv castanets src
        cd ./src
    branches: [ "main" ]
  pull_request: $ build/install-build-deps.sh
  $ build/create_gclient.sh
 $ gclient sync --with_branch_head
 $ gn gen --args='enable_castanets=true enable_nacl=false is_debug=false' out/Default
 remove_webcore_debug_symbols=true
is_component_build=true
use_jumbo_build=true
$ autoninja -C out/Default chrome
$ build/install-build-deps-android.sh
$ build/create_gclient.sh
echo "target_os = [ 'android' ]" >> ../.gclient
$ gclient run-hooks
$ gclient sync --with_branch_head
$ gn gen --args='target_os="android" enable_castanets=true enable_nacl=false is_debug=false' out/Android
remove_webcore_debug_symbols=true
is_component_build=true
use_jumbo_build=true
$ autoninja -C out/Android chrome_public_apk
    branches: [ "main" ]

permissions: $ out/Default/chrome <URL> --enable-castanets
$ out/Default/chrome --type=renderer --enable-castanets=127.0.0.1
$ out/Default/chrome <URL> --enable-castanets
$ out/Default/chrome --type=renderer --enable-castanets=<BROWSER IP ADDR>
$ out/Default/chrome <URL> --enable-castanets
$(adb) echo "_ --type=renderer --enable-castanets="BROWSER IP ADDR"" > /data/local/tmp/chrome-command-line
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ _ }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ #!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm pre-commit }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
