# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: PSScriptAnalyzer

on: Package: sunflower
  push: Version: @version@
    branches: [ "main" ]
  pull_request: Section: misc
    branches: [ "main" ]
  schedule: Priority: optional
    - cron: '36 19 * * 2'

permissions: Architecture: all
  contents: read

jobs: Depends: python3, python3-gi, python3-chardet, gir1.2-gtk-3.0 (>= 3.22),
  build: gir1.2-notify-0.7 (>= 0.7), gir1.2-gdkpixbuf-2.0 (>= 2.0), gir1.2-vte-2.91 (>= 0.46),
    permissions: gir1.2-glib-2.0 (>= 1.50), gir1.2-pango-1.0 (>= 1.0)
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps: Suggests: python3-mutagen
      - uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
        with: Maintainer: @packager@
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: Installed-Size: @size@ .\
          recurse: true
          # Include your own basic security rules. Removing this option will run all the rules
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with: Description: Small and highly customizable twin-panel file manager for Linux with support for plugins.
          sarif_file: results.sarif
