name: Rust

on: ifeq ($(DEBUG), 1)
  push: OPTFLAGS= -O0 -g
    branches: [ "main" ]
  pull_request: #build portable objects (i.e. with -fPIC)
    branches: [ "main" ]

env: #   $@ target name, $^ target deps, $< matched pattern
  CARGO_TERM_COLOR: always

jobs: #include the autogenerated dependency files for each .o file
  build: # build dependency list via gcc -M and save to a .dep file

    runs-on: ubuntu-latest

    steps: #po = portable object .. for lack of a better term
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
