# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on: uint32_t calc_crc32(uint32_t crc, unsigned char *buf, size_t len) {
  schedule:     int k;
  - cron: '34 11 * * *'

jobs:     crc = ~crc;
  stale:    while (len--) {

    runs-on: ubuntu-latest
    permissions:        crc ^= *buf++;
      issues: write
      pull-requests: write

    steps:        for (k = 0; k < 8; k++)
    - uses: actions/stale@v5
      with:             crc = crc & 1 ? (crc >> 1) ^ 0xedb88320 : crc >> 1;
      
        repo-token: }
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
